# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 399)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 574, 381))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ImageLbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ImageLbl.setFrameShape(QtWidgets.QFrame.Box)
        self.ImageLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ImageLbl.setObjectName("ImageLbl")
        self.verticalLayout_5.addWidget(self.ImageLbl)
        self.labelNama = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelNama.setFont(font)
        self.labelNama.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelNama.setText("")
        self.labelNama.setObjectName("labelNama")
        self.verticalLayout_5.addWidget(self.labelNama)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setWordWrap(True)
        self.label_7.setIndent(-1)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.labelRiset = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelRiset.setFont(font)
        self.labelRiset.setText("")
        self.labelRiset.setObjectName("labelRiset")
        self.verticalLayout_5.addWidget(self.labelRiset)
        self.labelAlamat = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.labelAlamat.setFont(font)
        self.labelAlamat.setText("")
        self.labelAlamat.setObjectName("labelAlamat")
        self.verticalLayout_5.addWidget(self.labelAlamat)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditNama = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditNama.setObjectName("lineEditNama")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditNama)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditAlamat = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditAlamat.setObjectName("lineEditAlamat")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditAlamat)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.selectImageBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.selectImageBtn.setObjectName("selectImageBtn")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.selectImageBtn)
        self.lineEditRiset = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditRiset.setObjectName("lineEditRiset")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditRiset)
        self.verticalLayout.addLayout(self.formLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButtonSimpan = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSimpan.setObjectName("pushButtonSimpan")
        self.verticalLayout.addWidget(self.pushButtonSimpan)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.selectImageBtn.clicked.connect(self.setImage)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ImageLbl.setText(_translate("Form", "Gambar Profil"))
        self.label_7.setText(_translate("Form", "Universitas Jendral Achmad Yani Yogyakarta"))
        self.label.setText(_translate("Form", "Edit Profile"))
        self.label_2.setText(_translate("Form", "Nama Lengkap"))
        self.label_3.setText(_translate("Form", "Alamat"))
        self.label_4.setText(_translate("Form", "Fokus Riset"))
        self.selectImageBtn.setText(_translate("Form", "Pilih Gambar Profile"))
        self.pushButtonSimpan.setText(_translate("Form", "Simpan"))

    def setImage(self):
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Select Image","", "Image Files (*.png *.jpg *.jpeg *.bmp)")
        if fileName:
            pixmap = QtGui.QPixmap(fileName)
            pixmap = pixmap.scaled(self.ImageLbl.width(), self.ImageLbl.height(), QtCore.Qt.KeepAspectRatio)
            self.ImageLbl.setPixmap(pixmap)
            self.ImageLbl.setAlignment(QtCore.Qt.AlignCenter)

